### ISSUE TITLE
Ttl issue when it's timestamp (ttl > 30days)

### ISSUE THREAD

**Issue by kruggs** [sobstel/metaphore#13]
Hi, i'm using your nice library for our platform and i notice an issue :

When we set a ttl > 30days, your class Ttl convert in unix timestamp the value, then at the moment of save with setResult you add again time(). Obviously it will not work if the value is already a unix timestamp

`$obj->cache('aa', function({ return 'aaa'}, (time() + 24*60*60*365)))` => ttl generated : 2979400318 instead of 1505468441

@edit : my mistake i just realize your library handle this and i should not set the timestamp but only seconds :)

**Comment by sobstel** [comment]
Thanks, even if you figured it out yourself, I think I'll update docs (README) to make it clear enough.
