### ISSUE TITLE
Dead lock issue

### ISSUE THREAD

**Issue by lchenay** [sobstel/metaphore#15]
In case of fatal error, server restart... we can have a situation of dead lock issue.

Why not putting a ttl in the lock data and in case cache is not regenerating until this ttl, another thread is allow to get the lock and generate the cache.

**Comment by lchenay** [comment]
This seems to concern only FileStore.
Those lines: https://github.com/sobstel/metaphore/blob/master/src/Store/FileStore.php#L64-L73
Check file existence. They must check also ttl.

**Comment by sobstel** [comment]
@lchenay Thanks for your contribution and fixing this. It was quite a bug.
